---

- name: changes the existing zookeeper configs with kerberos
  hosts: zookeepers
  gather_facts: yes
  become: no
  tasks:
    - import_tasks: tasks/common_vars.yml

    - name: Set keberos keytab file and service principal name
      set_fact: 
        zookeeper_service_principal_keytabfile: "{{ keytabs_deployment_dir }}/{{ service_principal_login }}.keytab"
        zookeeper_service_principal: "{{ service_principal_login }}/{{ ansible_fqdn }}@{{ realm_name }}"

    - name: Generate zookeeper-server.jaas
      template:
        src=conf/zookeeper-server.jaas.j2
        dest='{{ zookeeper_home }}/conf/zookeeper-server.jaas'

    - name: Generate zookeeper-client.jaas
      template:
        src=conf/zookeeper-client.jaas.j2
        dest='{{ zookeeper_home }}/conf/zookeeper-client.jaas'

    - name: update conf/zookeeper-env.sh with Kerberos setting
      blockinfile:
        path: '{{ zookeeper_home }}/conf/zookeeper-env.sh'
        insertafter: EOF
        marker: "# {mark} ANSIBLE MANAGED BLOCK for Kerberos"
        block: |
          export SERVER_JVMFLAGS="\
            -Djava.security.auth.login.config={{ zookeeper_home }}/conf/zookeeper-server.jaas \
            ${SERVER_JVMFLAGS}"
          export CLIENT_JVMFLAGS="\
            -Dzookeeper.sasl.client=true \
            -Dzookeeper.sasl.client.username={{ service_principal_login }} \
            -Djava.security.auth.login.config={{ zookeeper_home }}/conf/zookeeper-client.jaas \
            ${CLIENT_JVMFLAGS}"
   
    - name: update conf/zoo.cfg with Kerberos setting
      blockinfile:
        path: '{{ zookeeper_home }}/conf/zoo.cfg'
        insertafter: EOF
        marker: "# {mark} ANSIBLE MANAGED BLOCK for Kerberos"
        block: |
          authProvider.1=org.apache.zookeeper.server.auth.SASLAuthenticationProvider
          jaasLoginRenew=3600000
          kerberos.removeHostFromPrincipal=true
          kerberos.removeRealmFromPrincipal=true
   


